Iter5
kelmik91/Y-URL-Shortening-Service pull request #5
Opened 2024-04-05 21:03 UTC by kelmik91

2024-04-10 22:49 UTC, avhitrov requested changes
Data Race при обращении к стораджу. Не реализован раутер (хотя бы chi).

2024-04-10 22:49 UTC, avhitrov commented on internal/handlers/handlers.go
> +
Нужна проверка входных данные на соответствие формату url. Хотя бы url.Parse.

2024-04-10 22:49 UTC, avhitrov commented on internal/storage/storage.go
> +var StorageURL = map[string]string{}
Мапы - структуры потоконебезопасные и в конкурентной среде (а http-сервер априори является конкурентным приложением, так как на каждый запрос пользователя хендлер открывается в отдельной горутине) должны защищаться блокировкой. Можно использовать либо sync.Mutex (sync.RWMutex), либо потокобезопасную мапу sync.Map.

https://t.me/bushigo/24

При одновременном чтении и записи имеем:
```
==================
WARNING: DATA RACE
Write at 0x00c000088000 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  github.com/kelmik91/Y-URL-Shortening-Service/internal/handlers.MainHandler()
      D:/work/src/github.com/kelmik91/Y-URL-Shortening-Service/internal/handlers/handlers.go:30 +0x6a7
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous read at 0x00c000088000 by goroutine 49:
  runtime.mapaccess2_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:108 +0x0
  github.com/kelmik91/Y-URL-Shortening-Service/internal/handlers.MainHandler()
      D:/work/src/github.com/kelmik91/Y-URL-Shortening-Service/internal/handlers/handlers.go:53 +0x330
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x35d
  github.com/kelmik91/Y-URL-Shortening-Service/internal/server.Run()
      D:/work/src/github.com/kelmik91/Y-URL-Shortening-Service/internal/server/server.go:15 +0x272
  main.main()
      D:/work/src/github.com/kelmik91/Y-URL-Shortening-Service/cmd/shortener/main.go:11 +0x3b

Goroutine 49 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x35d
  github.com/kelmik91/Y-URL-Shortening-Service/internal/server.Run()
      D:/work/src/github.com/kelmik91/Y-URL-Shortening-Service/internal/server/server.go:15 +0x272
  main.main()
      D:/work/src/github.com/kelmik91/Y-URL-Shortening-Service/cmd/shortener/main.go:11 +0x3b
==================
```
с последующим падением в панику
```
fatal error: concurrent map read and map write

goroutine 1877 [running]:
github.com/kelmik91/Y-URL-Shortening-Service/internal/handlers.MainHandler({0x140538550, 0xc0001d09a0}, 0xc0001f2480)
        D:/work/src/github.com/kelmik91/Y-URL-Shortening-Service/internal/handlers/handlers.go:53 +0x331
net/http.HandlerFunc.ServeHTTP(0x1404d8688, {0x140538550, 0xc0001d09a0}, 0xc0001f2480)
        C:/Apps/Go/src/net/http/server.go:2166 +0x48
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0000f6060, {0x140538550, 0xc0001d09a0}, 0xc0001f2480)
        C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x595
net/http.HandlerFunc.ServeHTTP(0xc00008a1b0, {0x140538550, 0xc0001d09a0}, 0xc0001f2480)
        C:/Apps/Go/src/net/http/server.go:2166 +0x48
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0000f6060, {0x140538550, 0xc0001d09a0}, 0xc0001f2360)
        C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x69f
net/http.serverHandler.ServeHTTP({0xc00028b4d0?}, {0x140538550, 0xc0001d09a0}, 0xc0001f2360)
        C:/Apps/Go/src/net/http/server.go:3137 +0x2a2
net/http.(*conn).serve(0xc000310630, {0x140538ab8, 0xc000088f30})
        C:/Apps/Go/src/net/http/server.go:2039 +0x13c5
created by net/http.(*Server).Serve in goroutine 1
        C:/Apps/Go/src/net/http/server.go:3285 +0x8ed
```

2024-04-11 20:58 UTC, kelmik91 commented on internal/handlers/handlers.go
> +
Добавил проверку url.ParseRequestURI

2024-04-11 20:59 UTC, kelmik91 commented on internal/storage/storage.go
> +var StorageURL = map[string]string{}
Переписал storage на структуру с sync.RWMutex

2024-04-15 23:03 UTC, avhitrov approved these changes
Все замечания устранены.

2024-04-17 19:04 UTC, merged